package com.aa.mtg.cards.ability;

import com.aa.mtg.cardinstance.ability.CardInstanceAbility;
import com.aa.mtg.cards.ability.selector.CardInstanceSelector;
import com.aa.mtg.cards.ability.selector.PowerToughnessConstraint;
import com.aa.mtg.cards.ability.selector.SelectorType;
import com.aa.mtg.cards.ability.target.Target;
import com.aa.mtg.cards.ability.type.AbilityType;
import com.aa.mtg.cards.properties.Color;

import java.util.List;
import java.util.Optional;

import static com.aa.mtg.cards.ability.selector.PowerToughnessConstraint.PowerOrToughness.POWER;
import static com.aa.mtg.cards.ability.selector.PowerToughnessConstraint.PowerOrToughness.TOUGHNESS;
import static com.aa.mtg.cards.ability.selector.PowerToughnessConstraintType.GREATER_OR_EQUAL;
import static com.aa.mtg.cards.ability.selector.PowerToughnessConstraintType.LESS_OR_EQUAL;
import static com.aa.mtg.cards.ability.selector.SelectorType.ANY;
import static com.aa.mtg.cards.ability.selector.SelectorType.PERMANENT;
import static com.aa.mtg.cards.ability.selector.StatusType.ATTACKING;
import static com.aa.mtg.cards.ability.selector.StatusType.BLOCKING;
import static com.aa.mtg.cards.ability.selector.TurnStatusType.YOUR_TURN;
import static com.aa.mtg.cards.ability.trigger.Trigger.*;
import static com.aa.mtg.cards.ability.trigger.TriggerSubtype.WHEN_DIE;
import static com.aa.mtg.cards.ability.trigger.TriggerSubtype.WHEN_ENTER_THE_BATTLEFIELD;
import static com.aa.mtg.cards.ability.type.AbilityType.*;
import static com.aa.mtg.cards.properties.Cost.*;
import static com.aa.mtg.cards.properties.Subtype.KNIGHT;
import static com.aa.mtg.cards.properties.Subtype.ZOMBIE;
import static com.aa.mtg.cards.properties.Type.*;
import static com.aa.mtg.player.PlayerType.OPPONENT;
import static com.aa.mtg.player.PlayerType.PLAYER;
import static java.util.Arrays.asList;
import static java.util.Collections.emptyList;
import static java.util.Collections.singletonList;
import static java.util.stream.Collectors.toList;

public class Abilities {
    public static final CardInstanceAbility ADAMANT_BLUE_ENTER_PLUS_1_COUNTER = new CardInstanceAbility(AbilityType.ADAMANT, singletonList("BLUE"), new CardInstanceAbility(AbilityType.ENTERS_THE_BATTLEFIELD_WITH, singletonList("PLUS_1_COUNTERS:1")));
    public static final CardInstanceAbility ADAMANT_RED_ENTER_PLUS_1_COUNTER = new CardInstanceAbility(AbilityType.ADAMANT, singletonList("RED"), new CardInstanceAbility(AbilityType.ENTERS_THE_BATTLEFIELD_WITH, singletonList("PLUS_1_COUNTERS:1")));
    public static final CardInstanceAbility ADAMANT_WHITE_ENTER_PLUS_1_COUNTER = new CardInstanceAbility(AbilityType.ADAMANT, singletonList("WHITE"), new CardInstanceAbility(AbilityType.ENTERS_THE_BATTLEFIELD_WITH, singletonList("PLUS_1_COUNTERS:1")));
    public static final CardInstanceAbility ADAMANT_SAME_ENTER_DRAW_A_CARD = new CardInstanceAbility(AbilityType.ADAMANT, singletonList("SAME"), new CardInstanceAbility(AbilityType.ENTERS_THE_BATTLEFIELD_WITH, singletonList("DRAW:1")));
    public static final CardInstanceAbility ADAMANT_SAME_ENTER_PLUS_1_COUNTER = new CardInstanceAbility(AbilityType.ADAMANT, singletonList("SAME"), new CardInstanceAbility(AbilityType.ENTERS_THE_BATTLEFIELD_WITH, singletonList("PLUS_1_COUNTERS:1")));
    public static final CardInstanceAbility AS_LONG_AS_IS_YOUR_TURN_IT_HAS_LIFELINK = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).turnStatusType(YOUR_TURN).build(), singletonList("LIFELINK"), staticAbility());
    public static final CardInstanceAbility CREATURES_YOU_CONTROL_GET_PLUS_1_1_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build(), singletonList("+1/+1"), castTrigger());
    public static final CardInstanceAbility CREATURES_YOU_CONTROL_GET_PLUS_2_0_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build(), singletonList("+2/+0"), castTrigger());
    public static final CardInstanceAbility CREATURES_YOU_CONTROL_GET_PLUS_2_1_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build(), singletonList("+2/+1"), castTrigger());
    public static final CardInstanceAbility CREATURES_YOU_CONTROL_GET_PLUS_2_2_AND_TRAMPLE_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build(), asList("+2/+2", "TRAMPLE"), castTrigger());
    public static final CardInstanceAbility CREATURES_YOU_CONTROL_GET_TRAMPLE_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, emptyList(), singletonList("TRAMPLE"), castTrigger());
    public static final CardInstanceAbility CREATURES_YOU_CONTROL_WITH_FLYING_GET_PLUS_1_1 = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).withAbilityType(AbilityType.FLYING).build(), singletonList("+1/+1"), staticAbility());
    public static final CardInstanceAbility DEAL_3_DAMAGE_TO_ANY_TARGET = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(SelectorType.ANY).build()).build()), singletonList("DAMAGE:3"), castTrigger());
    public static final CardInstanceAbility DEAL_1_DAMAGE_TO_CREATURE_YOU_CONTROL_THAT_CREATURE_GAINS_TRAMPLE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build()).build()), asList("DAMAGE:1", "TRAMPLE"), castTrigger());
    public static final CardInstanceAbility DEAL_4_DAMAGE_TO_TARGET_ATTACKING_OR_BLOCKING_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).statusTypes(asList(ATTACKING, BLOCKING)).build()).build()), singletonList("DAMAGE:4"), castTrigger());
    public static final CardInstanceAbility DEAL_3_DAMAGE_TO_TARGET_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("DAMAGE:3"), castTrigger());
    public static final CardInstanceAbility DEAL_4_DAMAGE_TO_TARGET_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("DAMAGE:4"), castTrigger());
    public static final CardInstanceAbility DEAL_4_DAMAGE_TO_TARGET_CREATURE_2_DAMAGE_TO_CONTROLLER = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("DAMAGE:4", "CONTROLLER_DAMAGE:2"), castTrigger());
    public static final CardInstanceAbility DEAL_5_DAMAGE_TO_TARGET_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("DAMAGE:5"), castTrigger());
    public static final CardInstanceAbility DEAL_5_DAMAGE_TO_TARGET_PLAYER_OR_PLANESWALKER = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(SelectorType.PLAYER).build()).build()), singletonList("DAMAGE:5"), castTrigger());
    public static final CardInstanceAbility DEAL_7_DAMAGE_TO_TARGET_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("DAMAGE:7"), castTrigger());
    public static final CardInstanceAbility DEATHTOUCH = new CardInstanceAbility(AbilityType.DEATHTOUCH);
    public static final CardInstanceAbility DESTROY_TARGET_ARTIFACT_OR_CREATURE_OR_PLANESWALKER = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(asList(ARTIFACT, CREATURE, PLANESWALKER)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_ARTIFACT_OR_ENCHANTMENT = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(asList(ARTIFACT, ENCHANTMENT)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_ARTIFACT_OR_LAND = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(asList(ARTIFACT, LAND)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_ATTACKING_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).statusTypes(singletonList(ATTACKING)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_ATTACKING_OF_BLOCKING_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).statusTypes(asList(ATTACKING, BLOCKING)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_CREATURE_OR_ENCHANTMENT = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(asList(CREATURE, ENCHANTMENT)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_CREATURE_OR_PLANESWALKER_THAT_S_GREEN_OR_WHITE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(asList(CREATURE, PLANESWALKER)).ofColors(asList(Color.GREEN, Color.WHITE)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_CREATURE_WITH_POWER_GREATER_OR_EQUAL_4 = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).powerToughnessConstraint(new PowerToughnessConstraint(POWER, GREATER_OR_EQUAL, 4)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_CREATURE_WITH_POWER_LESS_OR_EQUAL_3 = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).powerToughnessConstraint(new PowerToughnessConstraint(POWER, LESS_OR_EQUAL, 3)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_CREATURE_WITH_TOUGHNESS_GREATER_OR_EQUAL_4 = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).powerToughnessConstraint(new PowerToughnessConstraint(TOUGHNESS, GREATER_OR_EQUAL, 4)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility DESTROY_TARGET_CREATURE_2_DAMAGE_TO_CONTROLLER = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList(":DESTROYED", "CONTROLLER_DAMAGE:2"), castTrigger());
    public static final CardInstanceAbility DRAW_1_CARD = new CardInstanceAbility(DRAW_X_CARDS, emptyList(), singletonList("1"), castTrigger());
    public static final CardInstanceAbility DRAW_2_CARDS = new CardInstanceAbility(DRAW_X_CARDS, emptyList(), singletonList("2"), castTrigger());
    public static final CardInstanceAbility ENCHANTED_CREATURE_GETS_FLYING = new CardInstanceAbility(ENCHANTED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("FLYING"), castTrigger());
    public static final CardInstanceAbility ENCHANTED_CREATURE_GETS_PLUS_1_1_AND_FLYING = new CardInstanceAbility(ENCHANTED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+1/+1", "FLYING"), castTrigger());
    public static final CardInstanceAbility ENCHANTED_CREATURE_GETS_PLUS_2_2_AND_FLYING = new CardInstanceAbility(ENCHANTED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+2/+2", "FLYING"), castTrigger());
    public static final CardInstanceAbility ENCHANTED_CREATURE_GETS_PLUS_2_2_AND_HASTE = new CardInstanceAbility(ENCHANTED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+2/+2", "HASTE"), castTrigger());
    public static final CardInstanceAbility ENCHANTED_CREATURE_GETS_PLUS_2_2_AND_LIFELINK = new CardInstanceAbility(ENCHANTED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+2/+2", "LIFELINK"), castTrigger());
    public static final CardInstanceAbility ENCHANTED_CREATURE_GETS_PLUS_3_2_AND_VIGILANCE = new CardInstanceAbility(ENCHANTED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+3/+2", "VIGILANCE"), castTrigger());
    public static final CardInstanceAbility ENCHANTED_CREATURE_GETS_PLUS_3_3 = new CardInstanceAbility(ENCHANTED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+3/+3"), castTrigger());
    public static final CardInstanceAbility ENCHANTED_CREATURE_GETS_PLUS_7_7_AND_TRAMPLE = new CardInstanceAbility(ENCHANTED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+7/+7", "TRAMPLE"), castTrigger());
    public static final CardInstanceAbility ENCHANTED_CREATURE_GETS_MINUS_2_2 = new CardInstanceAbility(ENCHANTED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("-2/-2"), castTrigger());
    public static final CardInstanceAbility ENTERS_THE_BATTLEFIELD_TAPPED = new CardInstanceAbility(AbilityType.ENTERS_THE_BATTLEFIELD_WITH, singletonList(":TAPPED"));
    public static final CardInstanceAbility FLYING = new CardInstanceAbility(AbilityType.FLYING);
    public static final CardInstanceAbility GAIN_CONTROL_TARGET_CREATURE_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).notOfType(singletonList(LAND)).build()).build()), singletonList(":CONTROLLED"), castTrigger());
    public static final CardInstanceAbility GAIN_1_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("1"), castTrigger());
    public static final CardInstanceAbility GAIN_2_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("2"), castTrigger());
    public static final CardInstanceAbility GAIN_3_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("3"), castTrigger());
    public static final CardInstanceAbility GAIN_4_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("4"), castTrigger());
    public static final CardInstanceAbility HASTE = new CardInstanceAbility(AbilityType.HASTE);
    public static final CardInstanceAbility LIFELINK = new CardInstanceAbility(AbilityType.LIFELINK);
    public static final CardInstanceAbility LOSE_4_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("-4"), castTrigger());
    public static final CardInstanceAbility OTHER_CREATURES_YOU_CONTROL_GET_PLUS_1_0 = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).others(true).build(), singletonList("+1/+0"), staticAbility());
    public static final CardInstanceAbility OTHER_CREATURES_YOU_CONTROL_GET_PLUS_1_1 = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).others(true).build(), singletonList("+1/+1"), staticAbility());
    public static final CardInstanceAbility OTHER_CREATURES_YOU_CONTROL_GET_TRAMPLE = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).others(true).build(), singletonList("TRAMPLE"), staticAbility());
    public static final CardInstanceAbility OTHER_CREATURES_YOU_CONTROL_WITH_FLYING_GET_PLUS_0_1 = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).withAbilityType(AbilityType.FLYING).others(true).build(), singletonList("+0/+1"), staticAbility());
    public static final CardInstanceAbility OTHER_CREATURES_YOU_CONTROL_WITH_FLYING_GET_PLUS_1_0 = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).withAbilityType(AbilityType.FLYING).others(true).build(), singletonList("+1/+0"), staticAbility());
    public static final CardInstanceAbility OTHER_CREATURES_YOU_CONTROL_WITH_FLYING_GET_PLUS_1_1 = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).withAbilityType(AbilityType.FLYING).others(true).build(), singletonList("+1/+1"), staticAbility());
    public static final CardInstanceAbility OTHER_KNIGHTS_YOU_CONTROL_GET_PLUS_1_1 = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).ofSubtypeOf(singletonList(KNIGHT)).controllerType(PLAYER).others(true).build(), singletonList("+1/+1"), staticAbility());
    public static final CardInstanceAbility OTHER_ZOMBIES_YOU_CONTROL_GET_DEATHTOUCH = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).ofSubtypeOf(singletonList(ZOMBIE)).controllerType(PLAYER).others(true).build(), singletonList("DEATHTOUCH"), staticAbility());
    public static final CardInstanceAbility OTHER_ZOMBIES_YOU_CONTROL_GET_PLUS_1_1 = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).ofSubtypeOf(singletonList(ZOMBIE)).controllerType(PLAYER).others(true).build(), singletonList("+1/+1"), staticAbility());
    public static final CardInstanceAbility PAY_BLACK_IT_GETS_PLUS_1_PLUS_1_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+1/+1"), activatedAbility(singletonList(BLACK)));
    public static final CardInstanceAbility PAY_BLACK_IT_GETS_DEATHTOUCH_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("DEATHTOUCH"), activatedAbility(singletonList(BLACK)));
    public static final CardInstanceAbility PAY_BLUE_IT_GETS_PLUS_1_MINUS_1_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+1/-1"), activatedAbility(singletonList(BLUE)));
    public static final CardInstanceAbility PAY_1_RED_IT_GETS_PLUS_1_PLUS_0_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+1/+0"), activatedAbility(singletonList(RED)));
    public static final CardInstanceAbility PAY_1_RED_IT_GETS_PLUS_2_PLUS_0_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+2/+0"), activatedAbility(singletonList(RED)));
    public static final CardInstanceAbility PAY_1_EQUIP_CREATURE_GETS_FLYING = new CardInstanceAbility(EQUIPPED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("FLYING"), activatedAbility(singletonList(COLORLESS)));
    public static final CardInstanceAbility PAY_1_EQUIP_CREATURE_GETS_PLUS_1_1 = new CardInstanceAbility(EQUIPPED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+1/+1"), activatedAbility(singletonList(COLORLESS)));
    public static final CardInstanceAbility PAY_1_EQUIP_CREATURE_GETS_PLUS_1_0_AND_HASTE = new CardInstanceAbility(EQUIPPED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+1/+0", "HASTE"), activatedAbility(singletonList(COLORLESS)));
    public static final CardInstanceAbility PAY_1_EQUIP_CREATURE_GETS_PLUS_1_1_AND_HASTE = new CardInstanceAbility(EQUIPPED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+1/+1", "HASTE"), activatedAbility(singletonList(COLORLESS)));
    public static final CardInstanceAbility PAY_2_EQUIP_CREATURE_GETS_PLUS_2_0 = new CardInstanceAbility(EQUIPPED_CREATURE_GETS, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+2/+0"), activatedAbility(asList(COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_1_IT_GETS_PLUS_HASTE_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("HASTE"), activatedAbility(singletonList(COLORLESS)));
    public static final CardInstanceAbility PAY_1_1_BLACK_IT_GETS_PLUS_1_PLUS_1_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+1/+1"), activatedAbility(asList(RED, COLORLESS)));
    public static final CardInstanceAbility PAY_1_1_RED_IT_GETS_PLUS_1_PLUS_0_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+1/+0"), activatedAbility(asList(RED, COLORLESS)));
    public static final CardInstanceAbility PAY_1_1_RED_IT_GETS_PLUS_2_PLUS_0_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+2/+0"), activatedAbility(asList(RED, COLORLESS)));
    public static final CardInstanceAbility PAY_1_1_WHITE_IT_GETS_VIGILANCE_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("VIGILANCE"), activatedAbility(asList(WHITE, COLORLESS)));
    public static final CardInstanceAbility PAY_1_2_RED_DEAL_1_DAMAGE_TO_TARGET_PLAYER = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(SelectorType.PLAYER).build()).build()), singletonList("DAMAGE:1"), activatedAbility(asList(RED, RED, COLORLESS)));
    public static final CardInstanceAbility PAY_2_1_BLACK_IT_GETS_PLUS_1_PLUS_1_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+1/+1"), activatedAbility(asList(BLACK, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_2_1_RED_IT_GETS_PLUS_3_PLUS_0_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+3/+0"), activatedAbility(asList(RED, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_3_IT_GETS_PLUS_1_PLUS_0_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+1/+0"), activatedAbility(asList(COLORLESS, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_3_1_GREEN_IT_GETS_PLUS_1_PLUS_0_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+1/+0"), activatedAbility(asList(COLORLESS, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_3_1_GREEN_PUT_A_PLUS_1_COUNTER_ON_IT = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("PLUS_1_COUNTERS:1"), activatedAbility(asList(COLORLESS, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_3_1_BLUE_IT_GETS_FLYING_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("FLYING"), activatedAbility(asList(BLUE, COLORLESS, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_3_1_WHITE_PUT_A_PLUS_1_COUNTER_ON_TARGET_CREATURE_YOU_CONTROL = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).withAbilityType(AbilityType.FLYING).build()).build()), singletonList("PLUS_1_COUNTERS:1"), activatedAbility(asList(WHITE, COLORLESS, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_3_2_BLUE_DRAW_2_CARDS = new CardInstanceAbility(DRAW_X_CARDS, emptyList(), singletonList("2"), activatedAbility(asList(BLUE, BLUE, COLORLESS, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_4_IT_GETS_PLUS_2_PLUS_0_AND_FLYING_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), asList("+2/+0", "FLYING"), activatedAbility(asList(COLORLESS, COLORLESS, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PAY_4_1_RED_IT_GETS_PLUS_2_PLUS_2_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+2/+2"), activatedAbility(asList(GREEN, COLORLESS, COLORLESS, COLORLESS, COLORLESS)));
    public static final CardInstanceAbility PUT_A_PLUS_1_COUNTER_UP_TO_2_TARGET_CREATURES = new CardInstanceAbility(THAT_TARGETS_GET, asList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).optional(true).build(), Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).optional(true).other(true).build()), singletonList("PLUS_1_COUNTERS:1"), castTrigger());
    public static final CardInstanceAbility REACH = new CardInstanceAbility(AbilityType.REACH);
    public static final CardInstanceAbility RETURN_TARGET_NONLAND_TO_ITS_OWNER_HAND = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).notOfType(singletonList(LAND)).build()).build()), singletonList(":RETURN_TO_OWNER_HAND"), castTrigger());
    public static final CardInstanceAbility SHUFFLE_GRAVEYARD_INTO_LIBRARY_OF_TARGET_PLAYER = new CardInstanceAbility(SHUFFLE_GRAVEYARD_INTO_LIBRARY_FOR_TARGET_PLAYER, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(SelectorType.PLAYER).build()).build()), emptyList(), castTrigger());
    public static final CardInstanceAbility SKELETON_YOU_CONTROL_GET_DEATHTOUCH = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).ofSubtypeOf(singletonList(ZOMBIE)).controllerType(PLAYER).build(), singletonList("DEATHTOUCH"), staticAbility());
    public static final CardInstanceAbility SKELETON_YOU_CONTROL_GET_PLUS_1_1 = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).ofSubtypeOf(singletonList(ZOMBIE)).controllerType(PLAYER).build(), singletonList("+1/+1"), staticAbility());
    public static final CardInstanceAbility TAP_ADD_BLACK_MANA = new CardInstanceAbility(TAP_ADD_MANA, emptyList(), singletonList("BLACK"), manaAbilityTrigger());
    public static final CardInstanceAbility TAP_ADD_BLUE_MANA = new CardInstanceAbility(TAP_ADD_MANA, emptyList(), singletonList("BLUE"), manaAbilityTrigger());
    public static final CardInstanceAbility TAP_ADD_GREEN_MANA = new CardInstanceAbility(TAP_ADD_MANA, emptyList(), singletonList("GREEN"), manaAbilityTrigger());
    public static final CardInstanceAbility TAP_ADD_1_GREEN_1_BLUE_MANA = new CardInstanceAbility(TAP_ADD_MANA, emptyList(), asList("GREEN", "BLUE"), manaAbilityTrigger());
    public static final CardInstanceAbility TAP_ADD_RED_MANA = new CardInstanceAbility(TAP_ADD_MANA, emptyList(), singletonList("RED"), manaAbilityTrigger());
    public static final CardInstanceAbility TAP_ADD_WHITE_MANA = new CardInstanceAbility(TAP_ADD_MANA, emptyList(), singletonList("WHITE"), manaAbilityTrigger());
    public static final CardInstanceAbility TARGET_BLOCKING_CREATURE_GETS_PLUS_7_7_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).statusTypes(singletonList(BLOCKING)).build()).build()), singletonList("+7/+7"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_DEATHTOUCH_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("DEATHTOUCH"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_HASTE_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("HASTE"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_MINUS_2_2_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("-2/-2"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_1_0_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+1/+0"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_1_1_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+1/+1"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_1_3_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+1/+3"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_1_7_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+1/+7"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_2_1_AND_DEATHTOUCH_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+2/+1", "DEATHTOUCH"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_2_2_AND_FLYING_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+2/+2", "FLYING"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_2_2_AND_LIFELINK_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+2/+2", "LIFELINK"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_3_2_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+3/+2"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_3_3_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+3/+3"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_3_3_AND_REACH_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+3/+3", "REACH"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_PLUS_3_3_AND_TRAMPLE_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), asList("+3/+3", "TRAMPLE"), castTrigger());
    public static final CardInstanceAbility TARGET_CREATURE_GETS_MINUS_4_0_UNTIL_END_OF_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("-4/-0"), castTrigger());
    public static final CardInstanceAbility TARGET_ENCHANTMENT_GETS_DESTROYED = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(ENCHANTMENT)).build()).build()), singletonList(":DESTROYED"), castTrigger());
    public static final CardInstanceAbility TARGET_PLAYER_DRAWS_7_CARDS = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(SelectorType.PLAYER).build()).build()), singletonList("DRAW:7"), castTrigger());
    public static final CardInstanceAbility TRAMPLE = new CardInstanceAbility(AbilityType.TRAMPLE);
    public static final CardInstanceAbility UNTAP_TARGET_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList(":UNTAPPED"), castTrigger());
    public static final CardInstanceAbility VIGILANCE = new CardInstanceAbility(AbilityType.VIGILANCE);
    public static final CardInstanceAbility WHEN_IT_DIES_DRAW_1_CARD = new CardInstanceAbility(DRAW_X_CARDS, emptyList(), singletonList("1"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_DIES_GAIN_2_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("2"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_DIES_EACH_OPPONENTS_LOSES_2_LIFE = new CardInstanceAbility(EACH_PLAYERS_ADD_X_LIFE, emptyList(), singletonList("-2"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_DIES_IT_DEALS_1_DAMAGE_TO_ANY_TARGET = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(ANY).build()).build()), singletonList("DAMAGE:1"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_DIES_PUT_A_PLUS_1_COUNTER_ON_TARGET_CREATURE_YOU_CONTROL = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("PLUS_1_COUNTERS:1"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_DIES_PUT_A_PLUS_1_COUNTER_ON_TARGET_KNIGHT_YOU_CONTROL = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).ofSubtypeOf(singletonList(KNIGHT)).build()).build()), singletonList("PLUS_1_COUNTERS:1"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_DIES_RETURN_IT_TO_ITS_OWNER_HAND = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(ANY).build()).build()), singletonList(":RETURN_TO_OWNER_HAND"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_ANOTHER_TARGET_CREATURE_YOU_CONTROL_GETS_PLUS_1_1_AND_FLYING = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().others(true).selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build()).build()), asList("+1/+1", "Flying"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_ANY_TARGET_GET_1_DAMAGE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(SelectorType.ANY).build()).build()), singletonList("DAMAGE:1"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_CREATURES_YOU_CONTROL_GET_PLUS_1_1_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build(), singletonList("+1/+1"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_CREATURES_YOU_CONTROL_GET_PLUS_1_1_AND_VIGILANCE_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build(), asList("+1/+1", "VIGILANCE"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_CREATURES_YOU_CONTROL_GET_PLUS_2_2_VIGILANCE_AND_TRAMPLE_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build(), asList("+2/+2", "VIGILANCE", "TRAMPLE"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_DESTROY_TARGET_OPPONENT_CREATURE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(OPPONENT).build()).build()), singletonList(":DESTROYED"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_DRAW_A_CARD = new CardInstanceAbility(DRAW_X_CARDS, emptyList(), singletonList("1"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_EACH_PLAYERS_GAIN_4_LIFE = new CardInstanceAbility(EACH_PLAYERS_ADD_X_LIFE, emptyList(), singletonList("4"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_GAIN_2_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("2"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_GAIN_3_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("3"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_GAIN_4_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("4"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_GAIN_5_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("5"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_LOSE_1_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("-1"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_OTHER_CREATURES_GET_1_DAMAGE = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).others(true).build(), singletonList("DAMAGE:1"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_OTHER_CREATURES_YOU_CONTROL_GET_TRAMPLE_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).others(true).build(), singletonList("TRAMPLE"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_OTHER_CREATURES_YOU_CONTROL_GET_VIGILANCE_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).others(true).build(), singletonList("VIGILANCE"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_TAP_TARGET_OPPONENT_CREATURE_DOES_NOT_UNTAP_NEXT_TURN = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(OPPONENT).build()).build()), singletonList(":TAPPED_DOES_NOT_UNTAP_NEXT_TURN"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_TARGET_CREATURE_GETS_PLUS_0_1 = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+0/+1"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_TARGET_CREATURE_GETS_PLUS_2_0 = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+2/+0"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_TARGET_CREATURE_GETS_PLUS_2_2 = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).build()).build()), singletonList("+2/+2"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_TARGET_CREATURE_YOU_CONTROL_GETS_PLUS_1_1 = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build()).build()), singletonList("+1/+1"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_TARGET_OPPONENT_LOSES_3_LIFE = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(SelectorType.PLAYER).controllerType(OPPONENT).build()).build()), singletonList("LIFE:-3"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_TARGET_NONLAND_OPPONENT_PERMANENT_GET_DESTROYED = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).notOfType(singletonList(LAND)).controllerType(OPPONENT).build()).build()), singletonList(":DESTROYED"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_RETURN_ANOTHER_TARGET_CREATURE_YOU_CONTROL_TO_ITS_OWNER_HAND = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().others(true).selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build()).build()), singletonList(":RETURN_TO_OWNER_HAND"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHEN_IT_ENTERS_THE_BATTLEFIELD_RETURN_TARGET_OPPONENT_CREATURE_TO_ITS_OWNERS_HAND = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(OPPONENT).build()).build()), singletonList(":RETURN_TO_OWNER_HAND"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build()));
    public static final CardInstanceAbility WHENEVER_ANOTHER_CREATURE_DIES_EACH_OPPONENT_LOSES_1_LIFE = new CardInstanceAbility(EACH_PLAYERS_ADD_X_LIFE, emptyList(), singletonList("-1"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).others(true).build()));
    public static final CardInstanceAbility WHENEVER_ANOTHER_CREATURE_OR_PLANESWALKER_DIES_PUT_1_PLUS_1_COUNTER_ON_IT = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("PLUS_1_COUNTERS:1"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(asList(CREATURE, PLANESWALKER)).others(true).build()));
    public static final CardInstanceAbility WHENEVER_A_CREATURE_ENTERS_THE_BATTLEFIELD_UNDER_YOUR_CONTROL_YOU_GAIN_1_LIFE = new CardInstanceAbility(ADD_X_LIFE, emptyList(), singletonList("1"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build()));
    public static final CardInstanceAbility WHENEVER_A_CREATURE_ENTERS_THE_BATTLEFIELD_UNDER_YOUR_CONTROL_IT_GETS_PLUS_1_1_UNTIL_END_OF_TURN = new CardInstanceAbility(SELECTED_PERMANENTS_GET, CardInstanceSelector.builder().selectorType(PERMANENT).itself(true).build(), singletonList("+1/+1"), triggeredAbility(WHEN_ENTER_THE_BATTLEFIELD, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).controllerType(PLAYER).build()));
    public static final CardInstanceAbility WHENEVER_A_NON_TOKEN_CREATURE_YOU_CONTROL_DIES_IT_DEALS_1_DAMAGE_TO_ANY_TARGET = new CardInstanceAbility(THAT_TARGETS_GET, singletonList(Target.builder().cardInstanceSelector(CardInstanceSelector.builder().selectorType(SelectorType.ANY).build()).build()), singletonList("DAMAGE:1"), triggeredAbility(WHEN_DIE, CardInstanceSelector.builder().selectorType(PERMANENT).ofType(singletonList(CREATURE)).nonToken(true).build()));

    private static CardInstanceAbility get(String ability) {
        try {
            return (CardInstanceAbility) Abilities.class.getField(ability).get(null);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("Ability " + ability  + " does not exist.");
        }
    }

    public static List<CardInstanceAbility> abilitiesFromParameters(List<String> parameters) {
        return parameters.stream()
                .filter(parameter -> !parameter.contains("/") && !parameter.contains(":"))
                .map(Abilities::get)
                .collect(toList());
    }

    public static Optional<CardInstanceAbility> abilityFromParameter(String parameter) {
        List<CardInstanceAbility> abilities = abilitiesFromParameters(singletonList(parameter));
        if (abilities.isEmpty()) {
            return Optional.empty();
        } else {
            return Optional.of(abilities.get(0));
        }
    }
}
