package com.aa.mtg.cards.ability.type;

public enum AbilityType {
    CREATURES_YOU_CONTROL_GET_PLUS_X_X_UNTIL_END_OF_TURN,
    DEALS_X_DAMAGE_TO_TARGET,
    DEATHTOUCH,
    DESTROY_TARGET,
    DRAW_X_CARDS,
    FLYING,
    HASTE,
    REACH,
    SHUFFLE_GRAVEYARD_INTO_LIBRARY_FOR_TARGET_PLAYER,
    THAT_TARGETS_GET_X,
    TRAMPLE,
    VIGILANCE
}